language: python
python:
- '2.7.9'
cache: pip
before_install:
- sudo apt-get update -qq
install: 
- pip install -r requirements.txt
script:
- py.test --cov-report html --cov=src.main src/test/ --verbose
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: bh1SN6B7tY/2Ng+Wi9YcE1N+WXporRE60i33dKcMvqfh3QArtvYafKMU19V55VDd7afjRbHU8+zYlDthJQxQKkNLucjgw4k9esMl7OFTFiNh6Fsp6H1+gLb3ydSCOh7djTidhfqU636yFHlo5S8XzkJGL7tLRc4z0GISn0QiOmg9kFG6kFI+Hqew+qSyaa1vE5KELthmVUITGMX9O6mcAVGlcNwfMYv6ONhl065otzoaTsmC961XGPfsxsM7g7SihOd9SAglCKqb83seftevXWH5UAa7TYUC57oEnntk2h0jTLYQ9xzb2MSHupnWi5RSA4NlGp3y39qZDT2+PVpo91/5+VGVcI8T1n++XATkhhHCeQHyFdg1lOdzH5v81t2jGIoDR/oQOoODxOWgS6l6efcgNj2ArWDQgXTsRIhxd+EIwwciM/jN9CFJHOHCraJ6ZA2XAndNI56TA+Hy1WiohLIGyBiFmwTWTUkIe3Vl2jCvYkGLnyCAH8gjPEpXT8P8s1yj7tMkvUqK8Bd5Gh0Fc7XdraYfNaERymEZ/DghPqJGc45EOL0hsmyVkvsMWLbiiQouZ5FzcngglmH+/hE3F5qBjepf1aW1YfxVzHPL3lDcTK/DSqNLUEW+OUg7uPL+Jd+dCRNDAZf3JmFfn4KmHm+f+A0n3gMM4aOvhzwVxOc=
  app: fiuber-app-server
  on:
    repo: fi-ubers/app-server
